[package]
name = "nominatim"
version = "0.2.1"
edition = "2018"
authors = ["Grant Handy <grantshandy@gmail.com>"]
repository = "https://github.com/grantshandy/nominatim-rs"
documentation = "https://docs.rs/nominatim"
description = "A reverse geocoding API client powered by openstreetmap."
keywords = ["async", "coordinates", "nominatim", "geocoding", "location"]
categories = ["api-bindings", "asynchronous"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
surf = "2"
thiserror = "1"
serde = "1"
serde_json = "1"

[dev-dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }
